name: 🚀 续一次火

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"
      timezone: "Asia/Shanghai"

jobs:
  run:
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/playwright:v1.61.0-jammy
    timeout-minutes: 15

    steps:
      - name: 克隆当前仓库 (Clone current repo)
        uses: actions/checkout@v7

      - name: 安装 unzip (Install unzip)
        run: apt-get update && apt-get install -y unzip

      # - name: 安装 Python (Setup Python)
      #   uses: actions/setup-python@v7.0.0
      #   with:
      #     python-version: '3.13' 

      - name: 安装 Bun (Set up Bun)
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 安装运行时依赖 (Install dependencies)
        run: |
          bun install --production --ignore-scripts
#          apt-get update
#          apt-get install -y python3 python3-pip

      - name: 续一次火 (Run spark job)
        env:
          DOUYIN_COOKIE: ${{ secrets.DOUYIN_COOKIE }}
          DOUYIN_TARGET_NAMES: ${{ secrets.DOUYIN_TARGET_NAMES }}
          YIYAN_INCLUDE_SOURCE: ${{ secrets.YIYAN_INCLUDE_SOURCE }}
          SPARK_MESSAGE_TEMPLATE: ${{ secrets.SPARK_MESSAGE_TEMPLATE }}
        run: | 
          echo ${{ secrets.SPARK_MESSAGE_TEMPLATE }}
          bun src/main.ts

      # - name: 上传失败截图
      #   uses: actions/upload-artifact@v7.0.1
      #   with:
      #     path: artifacts/failure-screenshot.png

      - name: 发送构建失败通知
        if: failure()
        run: |
          curl -sS -X POST "https://sctapi.ftqq.com/${{ secrets.FTQQ_SENDKEY }}.send" \
            -d "title=可能未能正常续火花" \
            -d "desp=分支 ${{ github.ref_name }}，提交 ${{ github.sha }}，详情 ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: 发送构建成功通知
        if: success()
        run: |
          curl -sS -X POST "https://sctapi.ftqq.com/${{ secrets.FTQQ_SENDKEY }}.send" \
            -d "title=已完成今日自动续火花任务" \
            -d "desp=分支 ${{ github.ref_name }}，提交 ${{ github.sha }}，详情 ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
